Rails:
  Enabled: true
AllCops:
  TargetRubyVersion: 2.4
  TargetRailsVersion: 5.1
Metrics/LineLength:
  Max: 120
Metrics/ClassLength:
  Max: 200
Documentation:
  Enabled: false
Style/SignalException:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/FormatStringToken:
  EnforcedStyle: template
PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': ()
    '%w': ()
Metrics/ClassLength:
  Max: 200
Metrics/ModuleLength:
  Exclude:
    - '**/*_spec.rb'
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'
Rails/SkipsModelValidations:
  Exclude:
    - 'spec/**/*'
Rails/ApplicationRecord:
  Enabled: false
